# fly.toml app configuration file generated for homemade on 2023-06-07T14:18:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "homemade"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [env]
  PORT="3000"
  DB_URI="mongodb://localhost/fantasy-api"
  SECRET="our little secret"
  REACT_APP_CLOUDINARY_URL="https://api.cloudinary.com/v1_1/dqqidr9eg/image/upload"
  REACT_APP_CLOUDINARY_UPLOAD_PRESET="wo9bqtet"
